# GENETARED BY NNDCT, DO NOT EDIT!

import torch
from torch import tensor
import pytorch_nndct as py_nndct

class YOLOv3_qat(py_nndct.nn.NndctQuantModel):
    def __init__(self):
        super(YOLOv3_qat, self).__init__()
        self.module_0 = py_nndct.nn.Input() #YOLOv3_qat::input_0(YOLOv3_qat::nndct_input_0)
        self.module_1 = py_nndct.nn.quant_input() #YOLOv3_qat::YOLOv3_qat/QuantStub[quant_stub]/14623(YOLOv3_qat::nndct_quant_stub_1)
        self.module_2 = py_nndct.nn.Conv2d(in_channels=3, out_channels=32, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[0]/Conv2d[conv]/ret.5(YOLOv3_qat::nndct_conv2d_2)
        self.module_3 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[0]/LeakyReLU[leaky]/ret.9(YOLOv3_qat::nndct_leaky_relu_3)
        self.module_4 = py_nndct.nn.Conv2d(in_channels=32, out_channels=64, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[1]/Conv2d[conv]/ret.11(YOLOv3_qat::nndct_conv2d_4)
        self.module_5 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[1]/LeakyReLU[leaky]/ret.15(YOLOv3_qat::nndct_leaky_relu_5)
        self.module_6 = py_nndct.nn.Conv2d(in_channels=64, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[2]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/Conv2d[conv]/ret.17(YOLOv3_qat::nndct_conv2d_6)
        self.module_7 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[2]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/LeakyReLU[leaky]/ret.21(YOLOv3_qat::nndct_leaky_relu_7)
        self.module_8 = py_nndct.nn.Conv2d(in_channels=32, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[2]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/Conv2d[conv]/ret.23(YOLOv3_qat::nndct_conv2d_8)
        self.module_9 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[2]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/LeakyReLU[leaky]/ret.27(YOLOv3_qat::nndct_leaky_relu_9)
        self.module_10 = py_nndct.nn.Add() #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[2]/Add[skip_add]/ret.29(YOLOv3_qat::nndct_elemwise_add_10)
        self.module_11 = py_nndct.nn.Conv2d(in_channels=64, out_channels=128, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[3]/Conv2d[conv]/ret.31(YOLOv3_qat::nndct_conv2d_11)
        self.module_12 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[3]/LeakyReLU[leaky]/ret.35(YOLOv3_qat::nndct_leaky_relu_12)
        self.module_13 = py_nndct.nn.Conv2d(in_channels=128, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[4]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/Conv2d[conv]/ret.37(YOLOv3_qat::nndct_conv2d_13)
        self.module_14 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[4]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/LeakyReLU[leaky]/ret.41(YOLOv3_qat::nndct_leaky_relu_14)
        self.module_15 = py_nndct.nn.Conv2d(in_channels=64, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[4]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/Conv2d[conv]/ret.43(YOLOv3_qat::nndct_conv2d_15)
        self.module_16 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[4]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/LeakyReLU[leaky]/ret.47(YOLOv3_qat::nndct_leaky_relu_16)
        self.module_17 = py_nndct.nn.Add() #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[4]/Add[skip_add]/ret.49(YOLOv3_qat::nndct_elemwise_add_17)
        self.module_18 = py_nndct.nn.Conv2d(in_channels=128, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[4]/Sequential[layers]/ModuleList[1]/CNNBlock[0]/Conv2d[conv]/ret.51(YOLOv3_qat::nndct_conv2d_18)
        self.module_19 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[4]/Sequential[layers]/ModuleList[1]/CNNBlock[0]/LeakyReLU[leaky]/ret.55(YOLOv3_qat::nndct_leaky_relu_19)
        self.module_20 = py_nndct.nn.Conv2d(in_channels=64, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[4]/Sequential[layers]/ModuleList[1]/CNNBlock[1]/Conv2d[conv]/ret.57(YOLOv3_qat::nndct_conv2d_20)
        self.module_21 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[4]/Sequential[layers]/ModuleList[1]/CNNBlock[1]/LeakyReLU[leaky]/ret.61(YOLOv3_qat::nndct_leaky_relu_21)
        self.module_22 = py_nndct.nn.Add() #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[4]/Add[skip_add]/ret.63(YOLOv3_qat::nndct_elemwise_add_22)
        self.module_23 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[5]/Conv2d[conv]/ret.65(YOLOv3_qat::nndct_conv2d_23)
        self.module_24 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[5]/LeakyReLU[leaky]/ret.69(YOLOv3_qat::nndct_leaky_relu_24)
        self.module_25 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/Conv2d[conv]/ret.71(YOLOv3_qat::nndct_conv2d_25)
        self.module_26 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/LeakyReLU[leaky]/ret.75(YOLOv3_qat::nndct_leaky_relu_26)
        self.module_27 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/Conv2d[conv]/ret.77(YOLOv3_qat::nndct_conv2d_27)
        self.module_28 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/LeakyReLU[leaky]/ret.81(YOLOv3_qat::nndct_leaky_relu_28)
        self.module_29 = py_nndct.nn.Add() #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Add[skip_add]/ret.83(YOLOv3_qat::nndct_elemwise_add_29)
        self.module_30 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[1]/CNNBlock[0]/Conv2d[conv]/ret.85(YOLOv3_qat::nndct_conv2d_30)
        self.module_31 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[1]/CNNBlock[0]/LeakyReLU[leaky]/ret.89(YOLOv3_qat::nndct_leaky_relu_31)
        self.module_32 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[1]/CNNBlock[1]/Conv2d[conv]/ret.91(YOLOv3_qat::nndct_conv2d_32)
        self.module_33 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[1]/CNNBlock[1]/LeakyReLU[leaky]/ret.95(YOLOv3_qat::nndct_leaky_relu_33)
        self.module_34 = py_nndct.nn.Add() #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Add[skip_add]/ret.97(YOLOv3_qat::nndct_elemwise_add_34)
        self.module_35 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[2]/CNNBlock[0]/Conv2d[conv]/ret.99(YOLOv3_qat::nndct_conv2d_35)
        self.module_36 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[2]/CNNBlock[0]/LeakyReLU[leaky]/ret.103(YOLOv3_qat::nndct_leaky_relu_36)
        self.module_37 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[2]/CNNBlock[1]/Conv2d[conv]/ret.105(YOLOv3_qat::nndct_conv2d_37)
        self.module_38 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[2]/CNNBlock[1]/LeakyReLU[leaky]/ret.109(YOLOv3_qat::nndct_leaky_relu_38)
        self.module_39 = py_nndct.nn.Add() #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Add[skip_add]/ret.111(YOLOv3_qat::nndct_elemwise_add_39)
        self.module_40 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[3]/CNNBlock[0]/Conv2d[conv]/ret.113(YOLOv3_qat::nndct_conv2d_40)
        self.module_41 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[3]/CNNBlock[0]/LeakyReLU[leaky]/ret.117(YOLOv3_qat::nndct_leaky_relu_41)
        self.module_42 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[3]/CNNBlock[1]/Conv2d[conv]/ret.119(YOLOv3_qat::nndct_conv2d_42)
        self.module_43 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[3]/CNNBlock[1]/LeakyReLU[leaky]/ret.123(YOLOv3_qat::nndct_leaky_relu_43)
        self.module_44 = py_nndct.nn.Add() #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Add[skip_add]/ret.125(YOLOv3_qat::nndct_elemwise_add_44)
        self.module_45 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[4]/CNNBlock[0]/Conv2d[conv]/ret.127(YOLOv3_qat::nndct_conv2d_45)
        self.module_46 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[4]/CNNBlock[0]/LeakyReLU[leaky]/ret.131(YOLOv3_qat::nndct_leaky_relu_46)
        self.module_47 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[4]/CNNBlock[1]/Conv2d[conv]/ret.133(YOLOv3_qat::nndct_conv2d_47)
        self.module_48 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[4]/CNNBlock[1]/LeakyReLU[leaky]/ret.137(YOLOv3_qat::nndct_leaky_relu_48)
        self.module_49 = py_nndct.nn.Add() #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Add[skip_add]/ret.139(YOLOv3_qat::nndct_elemwise_add_49)
        self.module_50 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[5]/CNNBlock[0]/Conv2d[conv]/ret.141(YOLOv3_qat::nndct_conv2d_50)
        self.module_51 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[5]/CNNBlock[0]/LeakyReLU[leaky]/ret.145(YOLOv3_qat::nndct_leaky_relu_51)
        self.module_52 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[5]/CNNBlock[1]/Conv2d[conv]/ret.147(YOLOv3_qat::nndct_conv2d_52)
        self.module_53 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[5]/CNNBlock[1]/LeakyReLU[leaky]/ret.151(YOLOv3_qat::nndct_leaky_relu_53)
        self.module_54 = py_nndct.nn.Add() #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Add[skip_add]/ret.153(YOLOv3_qat::nndct_elemwise_add_54)
        self.module_55 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[6]/CNNBlock[0]/Conv2d[conv]/ret.155(YOLOv3_qat::nndct_conv2d_55)
        self.module_56 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[6]/CNNBlock[0]/LeakyReLU[leaky]/ret.159(YOLOv3_qat::nndct_leaky_relu_56)
        self.module_57 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[6]/CNNBlock[1]/Conv2d[conv]/ret.161(YOLOv3_qat::nndct_conv2d_57)
        self.module_58 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[6]/CNNBlock[1]/LeakyReLU[leaky]/ret.165(YOLOv3_qat::nndct_leaky_relu_58)
        self.module_59 = py_nndct.nn.Add() #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Add[skip_add]/ret.167(YOLOv3_qat::nndct_elemwise_add_59)
        self.module_60 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[7]/CNNBlock[0]/Conv2d[conv]/ret.169(YOLOv3_qat::nndct_conv2d_60)
        self.module_61 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[7]/CNNBlock[0]/LeakyReLU[leaky]/ret.173(YOLOv3_qat::nndct_leaky_relu_61)
        self.module_62 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[7]/CNNBlock[1]/Conv2d[conv]/ret.175(YOLOv3_qat::nndct_conv2d_62)
        self.module_63 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[7]/CNNBlock[1]/LeakyReLU[leaky]/ret.179(YOLOv3_qat::nndct_leaky_relu_63)
        self.module_64 = py_nndct.nn.Add() #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[6]/Add[skip_add]/ret.181(YOLOv3_qat::nndct_elemwise_add_64)
        self.module_65 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[7]/Conv2d[conv]/ret.183(YOLOv3_qat::nndct_conv2d_65)
        self.module_66 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[7]/LeakyReLU[leaky]/ret.187(YOLOv3_qat::nndct_leaky_relu_66)
        self.module_67 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/Conv2d[conv]/ret.189(YOLOv3_qat::nndct_conv2d_67)
        self.module_68 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/LeakyReLU[leaky]/ret.193(YOLOv3_qat::nndct_leaky_relu_68)
        self.module_69 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/Conv2d[conv]/ret.195(YOLOv3_qat::nndct_conv2d_69)
        self.module_70 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/LeakyReLU[leaky]/ret.199(YOLOv3_qat::nndct_leaky_relu_70)
        self.module_71 = py_nndct.nn.Add() #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Add[skip_add]/ret.201(YOLOv3_qat::nndct_elemwise_add_71)
        self.module_72 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[1]/CNNBlock[0]/Conv2d[conv]/ret.203(YOLOv3_qat::nndct_conv2d_72)
        self.module_73 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[1]/CNNBlock[0]/LeakyReLU[leaky]/ret.207(YOLOv3_qat::nndct_leaky_relu_73)
        self.module_74 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[1]/CNNBlock[1]/Conv2d[conv]/ret.209(YOLOv3_qat::nndct_conv2d_74)
        self.module_75 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[1]/CNNBlock[1]/LeakyReLU[leaky]/ret.213(YOLOv3_qat::nndct_leaky_relu_75)
        self.module_76 = py_nndct.nn.Add() #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Add[skip_add]/ret.215(YOLOv3_qat::nndct_elemwise_add_76)
        self.module_77 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[2]/CNNBlock[0]/Conv2d[conv]/ret.217(YOLOv3_qat::nndct_conv2d_77)
        self.module_78 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[2]/CNNBlock[0]/LeakyReLU[leaky]/ret.221(YOLOv3_qat::nndct_leaky_relu_78)
        self.module_79 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[2]/CNNBlock[1]/Conv2d[conv]/ret.223(YOLOv3_qat::nndct_conv2d_79)
        self.module_80 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[2]/CNNBlock[1]/LeakyReLU[leaky]/ret.227(YOLOv3_qat::nndct_leaky_relu_80)
        self.module_81 = py_nndct.nn.Add() #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Add[skip_add]/ret.229(YOLOv3_qat::nndct_elemwise_add_81)
        self.module_82 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[3]/CNNBlock[0]/Conv2d[conv]/ret.231(YOLOv3_qat::nndct_conv2d_82)
        self.module_83 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[3]/CNNBlock[0]/LeakyReLU[leaky]/ret.235(YOLOv3_qat::nndct_leaky_relu_83)
        self.module_84 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[3]/CNNBlock[1]/Conv2d[conv]/ret.237(YOLOv3_qat::nndct_conv2d_84)
        self.module_85 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[3]/CNNBlock[1]/LeakyReLU[leaky]/ret.241(YOLOv3_qat::nndct_leaky_relu_85)
        self.module_86 = py_nndct.nn.Add() #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Add[skip_add]/ret.243(YOLOv3_qat::nndct_elemwise_add_86)
        self.module_87 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[4]/CNNBlock[0]/Conv2d[conv]/ret.245(YOLOv3_qat::nndct_conv2d_87)
        self.module_88 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[4]/CNNBlock[0]/LeakyReLU[leaky]/ret.249(YOLOv3_qat::nndct_leaky_relu_88)
        self.module_89 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[4]/CNNBlock[1]/Conv2d[conv]/ret.251(YOLOv3_qat::nndct_conv2d_89)
        self.module_90 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[4]/CNNBlock[1]/LeakyReLU[leaky]/ret.255(YOLOv3_qat::nndct_leaky_relu_90)
        self.module_91 = py_nndct.nn.Add() #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Add[skip_add]/ret.257(YOLOv3_qat::nndct_elemwise_add_91)
        self.module_92 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[5]/CNNBlock[0]/Conv2d[conv]/ret.259(YOLOv3_qat::nndct_conv2d_92)
        self.module_93 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[5]/CNNBlock[0]/LeakyReLU[leaky]/ret.263(YOLOv3_qat::nndct_leaky_relu_93)
        self.module_94 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[5]/CNNBlock[1]/Conv2d[conv]/ret.265(YOLOv3_qat::nndct_conv2d_94)
        self.module_95 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[5]/CNNBlock[1]/LeakyReLU[leaky]/ret.269(YOLOv3_qat::nndct_leaky_relu_95)
        self.module_96 = py_nndct.nn.Add() #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Add[skip_add]/ret.271(YOLOv3_qat::nndct_elemwise_add_96)
        self.module_97 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[6]/CNNBlock[0]/Conv2d[conv]/ret.273(YOLOv3_qat::nndct_conv2d_97)
        self.module_98 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[6]/CNNBlock[0]/LeakyReLU[leaky]/ret.277(YOLOv3_qat::nndct_leaky_relu_98)
        self.module_99 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[6]/CNNBlock[1]/Conv2d[conv]/ret.279(YOLOv3_qat::nndct_conv2d_99)
        self.module_100 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[6]/CNNBlock[1]/LeakyReLU[leaky]/ret.283(YOLOv3_qat::nndct_leaky_relu_100)
        self.module_101 = py_nndct.nn.Add() #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Add[skip_add]/ret.285(YOLOv3_qat::nndct_elemwise_add_101)
        self.module_102 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[7]/CNNBlock[0]/Conv2d[conv]/ret.287(YOLOv3_qat::nndct_conv2d_102)
        self.module_103 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[7]/CNNBlock[0]/LeakyReLU[leaky]/ret.291(YOLOv3_qat::nndct_leaky_relu_103)
        self.module_104 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[7]/CNNBlock[1]/Conv2d[conv]/ret.293(YOLOv3_qat::nndct_conv2d_104)
        self.module_105 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[7]/CNNBlock[1]/LeakyReLU[leaky]/ret.297(YOLOv3_qat::nndct_leaky_relu_105)
        self.module_106 = py_nndct.nn.Add() #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[8]/Add[skip_add]/ret.299(YOLOv3_qat::nndct_elemwise_add_106)
        self.module_107 = py_nndct.nn.Conv2d(in_channels=512, out_channels=1024, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[9]/Conv2d[conv]/ret.301(YOLOv3_qat::nndct_conv2d_107)
        self.module_108 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[9]/LeakyReLU[leaky]/ret.305(YOLOv3_qat::nndct_leaky_relu_108)
        self.module_109 = py_nndct.nn.Conv2d(in_channels=1024, out_channels=512, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/Conv2d[conv]/ret.307(YOLOv3_qat::nndct_conv2d_109)
        self.module_110 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/LeakyReLU[leaky]/ret.311(YOLOv3_qat::nndct_leaky_relu_110)
        self.module_111 = py_nndct.nn.Conv2d(in_channels=512, out_channels=1024, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/Conv2d[conv]/ret.313(YOLOv3_qat::nndct_conv2d_111)
        self.module_112 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/LeakyReLU[leaky]/ret.317(YOLOv3_qat::nndct_leaky_relu_112)
        self.module_113 = py_nndct.nn.Add() #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[10]/Add[skip_add]/ret.319(YOLOv3_qat::nndct_elemwise_add_113)
        self.module_114 = py_nndct.nn.Conv2d(in_channels=1024, out_channels=512, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[1]/CNNBlock[0]/Conv2d[conv]/ret.321(YOLOv3_qat::nndct_conv2d_114)
        self.module_115 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[1]/CNNBlock[0]/LeakyReLU[leaky]/ret.325(YOLOv3_qat::nndct_leaky_relu_115)
        self.module_116 = py_nndct.nn.Conv2d(in_channels=512, out_channels=1024, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[1]/CNNBlock[1]/Conv2d[conv]/ret.327(YOLOv3_qat::nndct_conv2d_116)
        self.module_117 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[1]/CNNBlock[1]/LeakyReLU[leaky]/ret.331(YOLOv3_qat::nndct_leaky_relu_117)
        self.module_118 = py_nndct.nn.Add() #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[10]/Add[skip_add]/ret.333(YOLOv3_qat::nndct_elemwise_add_118)
        self.module_119 = py_nndct.nn.Conv2d(in_channels=1024, out_channels=512, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[2]/CNNBlock[0]/Conv2d[conv]/ret.335(YOLOv3_qat::nndct_conv2d_119)
        self.module_120 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[2]/CNNBlock[0]/LeakyReLU[leaky]/ret.339(YOLOv3_qat::nndct_leaky_relu_120)
        self.module_121 = py_nndct.nn.Conv2d(in_channels=512, out_channels=1024, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[2]/CNNBlock[1]/Conv2d[conv]/ret.341(YOLOv3_qat::nndct_conv2d_121)
        self.module_122 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[2]/CNNBlock[1]/LeakyReLU[leaky]/ret.345(YOLOv3_qat::nndct_leaky_relu_122)
        self.module_123 = py_nndct.nn.Add() #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[10]/Add[skip_add]/ret.347(YOLOv3_qat::nndct_elemwise_add_123)
        self.module_124 = py_nndct.nn.Conv2d(in_channels=1024, out_channels=512, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[3]/CNNBlock[0]/Conv2d[conv]/ret.349(YOLOv3_qat::nndct_conv2d_124)
        self.module_125 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[3]/CNNBlock[0]/LeakyReLU[leaky]/ret.353(YOLOv3_qat::nndct_leaky_relu_125)
        self.module_126 = py_nndct.nn.Conv2d(in_channels=512, out_channels=1024, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[3]/CNNBlock[1]/Conv2d[conv]/ret.355(YOLOv3_qat::nndct_conv2d_126)
        self.module_127 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[3]/CNNBlock[1]/LeakyReLU[leaky]/ret.359(YOLOv3_qat::nndct_leaky_relu_127)
        self.module_128 = py_nndct.nn.Add() #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[10]/Add[skip_add]/ret.361(YOLOv3_qat::nndct_elemwise_add_128)
        self.module_129 = py_nndct.nn.Conv2d(in_channels=1024, out_channels=512, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[11]/Conv2d[conv]/ret.363(YOLOv3_qat::nndct_conv2d_129)
        self.module_130 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[11]/LeakyReLU[leaky]/ret.367(YOLOv3_qat::nndct_leaky_relu_130)
        self.module_131 = py_nndct.nn.Conv2d(in_channels=512, out_channels=1024, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[12]/Conv2d[conv]/ret.369(YOLOv3_qat::nndct_conv2d_131)
        self.module_132 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[12]/LeakyReLU[leaky]/ret.373(YOLOv3_qat::nndct_leaky_relu_132)
        self.module_133 = py_nndct.nn.Conv2d(in_channels=1024, out_channels=512, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[13]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/Conv2d[conv]/ret.375(YOLOv3_qat::nndct_conv2d_133)
        self.module_134 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[13]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/LeakyReLU[leaky]/ret.379(YOLOv3_qat::nndct_leaky_relu_134)
        self.module_135 = py_nndct.nn.Conv2d(in_channels=512, out_channels=1024, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[13]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/Conv2d[conv]/ret.381(YOLOv3_qat::nndct_conv2d_135)
        self.module_136 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[13]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/LeakyReLU[leaky]/ret.385(YOLOv3_qat::nndct_leaky_relu_136)
        self.module_137 = py_nndct.nn.Conv2d(in_channels=1024, out_channels=512, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[14]/Conv2d[conv]/ret.387(YOLOv3_qat::nndct_conv2d_137)
        self.module_138 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[14]/LeakyReLU[leaky]/ret.391(YOLOv3_qat::nndct_leaky_relu_138)
        self.module_139 = py_nndct.nn.Module('nndct_shape') #YOLOv3_qat::YOLOv3_qat/ScalePrediction[layers]/ModuleList[15]/16407(YOLOv3_qat::nndct_shape_139)
        self.module_140 = py_nndct.nn.Module('nndct_shape') #YOLOv3_qat::YOLOv3_qat/ScalePrediction[layers]/ModuleList[15]/16413(YOLOv3_qat::nndct_shape_140)
        self.module_141 = py_nndct.nn.Module('nndct_shape') #YOLOv3_qat::YOLOv3_qat/ScalePrediction[layers]/ModuleList[15]/16416(YOLOv3_qat::nndct_shape_141)
        self.module_142 = py_nndct.nn.Conv2d(in_channels=512, out_channels=1024, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ScalePrediction[layers]/ModuleList[15]/Sequential[pred]/CNNBlock[0]/Conv2d[conv]/ret.393(YOLOv3_qat::nndct_conv2d_142)
        self.module_143 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ScalePrediction[layers]/ModuleList[15]/Sequential[pred]/CNNBlock[0]/LeakyReLU[leaky]/ret.397(YOLOv3_qat::nndct_leaky_relu_143)
        self.module_144 = py_nndct.nn.Conv2d(in_channels=1024, out_channels=75, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ScalePrediction[layers]/ModuleList[15]/Sequential[pred]/CNNBlock[1]/Conv2d[conv]/ret.399(YOLOv3_qat::nndct_conv2d_144)
        self.module_145 = py_nndct.nn.Module('nndct_reshape') #YOLOv3_qat::YOLOv3_qat/ScalePrediction[layers]/ModuleList[15]/ret.401(YOLOv3_qat::nndct_reshape_145)
        self.module_146 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[16]/Conv2d[conv]/ret.403(YOLOv3_qat::nndct_conv2d_146)
        self.module_147 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[16]/LeakyReLU[leaky]/ret.407(YOLOv3_qat::nndct_leaky_relu_147)
        self.module_148 = py_nndct.nn.Interpolate() #YOLOv3_qat::YOLOv3_qat/Upsample[layers]/ModuleList[17]/ret.409(YOLOv3_qat::nndct_resize_148)
        self.module_149 = py_nndct.nn.Cat() #YOLOv3_qat::YOLOv3_qat/Cat[concat]/ret.411(YOLOv3_qat::nndct_concat_149)
        self.module_150 = py_nndct.nn.Conv2d(in_channels=768, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[18]/Conv2d[conv]/ret.413(YOLOv3_qat::nndct_conv2d_150)
        self.module_151 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[18]/LeakyReLU[leaky]/ret.417(YOLOv3_qat::nndct_leaky_relu_151)
        self.module_152 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[19]/Conv2d[conv]/ret.419(YOLOv3_qat::nndct_conv2d_152)
        self.module_153 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[19]/LeakyReLU[leaky]/ret.423(YOLOv3_qat::nndct_leaky_relu_153)
        self.module_154 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[20]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/Conv2d[conv]/ret.425(YOLOv3_qat::nndct_conv2d_154)
        self.module_155 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[20]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/LeakyReLU[leaky]/ret.429(YOLOv3_qat::nndct_leaky_relu_155)
        self.module_156 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[20]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/Conv2d[conv]/ret.431(YOLOv3_qat::nndct_conv2d_156)
        self.module_157 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[20]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/LeakyReLU[leaky]/ret.435(YOLOv3_qat::nndct_leaky_relu_157)
        self.module_158 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[21]/Conv2d[conv]/ret.437(YOLOv3_qat::nndct_conv2d_158)
        self.module_159 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[21]/LeakyReLU[leaky]/ret.441(YOLOv3_qat::nndct_leaky_relu_159)
        self.module_160 = py_nndct.nn.Module('nndct_shape') #YOLOv3_qat::YOLOv3_qat/ScalePrediction[layers]/ModuleList[22]/16671(YOLOv3_qat::nndct_shape_160)
        self.module_161 = py_nndct.nn.Module('nndct_shape') #YOLOv3_qat::YOLOv3_qat/ScalePrediction[layers]/ModuleList[22]/16677(YOLOv3_qat::nndct_shape_161)
        self.module_162 = py_nndct.nn.Module('nndct_shape') #YOLOv3_qat::YOLOv3_qat/ScalePrediction[layers]/ModuleList[22]/16680(YOLOv3_qat::nndct_shape_162)
        self.module_163 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ScalePrediction[layers]/ModuleList[22]/Sequential[pred]/CNNBlock[0]/Conv2d[conv]/ret.443(YOLOv3_qat::nndct_conv2d_163)
        self.module_164 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ScalePrediction[layers]/ModuleList[22]/Sequential[pred]/CNNBlock[0]/LeakyReLU[leaky]/ret.447(YOLOv3_qat::nndct_leaky_relu_164)
        self.module_165 = py_nndct.nn.Conv2d(in_channels=512, out_channels=75, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ScalePrediction[layers]/ModuleList[22]/Sequential[pred]/CNNBlock[1]/Conv2d[conv]/ret.449(YOLOv3_qat::nndct_conv2d_165)
        self.module_166 = py_nndct.nn.Module('nndct_reshape') #YOLOv3_qat::YOLOv3_qat/ScalePrediction[layers]/ModuleList[22]/ret.451(YOLOv3_qat::nndct_reshape_166)
        self.module_167 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[23]/Conv2d[conv]/ret.453(YOLOv3_qat::nndct_conv2d_167)
        self.module_168 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[23]/LeakyReLU[leaky]/ret.457(YOLOv3_qat::nndct_leaky_relu_168)
        self.module_169 = py_nndct.nn.Interpolate() #YOLOv3_qat::YOLOv3_qat/Upsample[layers]/ModuleList[24]/ret.459(YOLOv3_qat::nndct_resize_169)
        self.module_170 = py_nndct.nn.Cat() #YOLOv3_qat::YOLOv3_qat/Cat[concat]/ret.461(YOLOv3_qat::nndct_concat_170)
        self.module_171 = py_nndct.nn.Conv2d(in_channels=384, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[25]/Conv2d[conv]/ret.463(YOLOv3_qat::nndct_conv2d_171)
        self.module_172 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[25]/LeakyReLU[leaky]/ret.467(YOLOv3_qat::nndct_leaky_relu_172)
        self.module_173 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[26]/Conv2d[conv]/ret.469(YOLOv3_qat::nndct_conv2d_173)
        self.module_174 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[26]/LeakyReLU[leaky]/ret.473(YOLOv3_qat::nndct_leaky_relu_174)
        self.module_175 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[27]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/Conv2d[conv]/ret.475(YOLOv3_qat::nndct_conv2d_175)
        self.module_176 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[27]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/LeakyReLU[leaky]/ret.479(YOLOv3_qat::nndct_leaky_relu_176)
        self.module_177 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[27]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/Conv2d[conv]/ret.481(YOLOv3_qat::nndct_conv2d_177)
        self.module_178 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ResidualBlock[layers]/ModuleList[27]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/LeakyReLU[leaky]/ret.485(YOLOv3_qat::nndct_leaky_relu_178)
        self.module_179 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[28]/Conv2d[conv]/ret.487(YOLOv3_qat::nndct_conv2d_179)
        self.module_180 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/CNNBlock[layers]/ModuleList[28]/LeakyReLU[leaky]/ret.491(YOLOv3_qat::nndct_leaky_relu_180)
        self.module_181 = py_nndct.nn.Module('nndct_shape') #YOLOv3_qat::YOLOv3_qat/ScalePrediction[layers]/ModuleList[29]/16935(YOLOv3_qat::nndct_shape_181)
        self.module_182 = py_nndct.nn.Module('nndct_shape') #YOLOv3_qat::YOLOv3_qat/ScalePrediction[layers]/ModuleList[29]/16941(YOLOv3_qat::nndct_shape_182)
        self.module_183 = py_nndct.nn.Module('nndct_shape') #YOLOv3_qat::YOLOv3_qat/ScalePrediction[layers]/ModuleList[29]/16944(YOLOv3_qat::nndct_shape_183)
        self.module_184 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ScalePrediction[layers]/ModuleList[29]/Sequential[pred]/CNNBlock[0]/Conv2d[conv]/ret.493(YOLOv3_qat::nndct_conv2d_184)
        self.module_185 = py_nndct.nn.LeakyReLU(negative_slope=0.1015625, inplace=False) #YOLOv3_qat::YOLOv3_qat/ScalePrediction[layers]/ModuleList[29]/Sequential[pred]/CNNBlock[0]/LeakyReLU[leaky]/ret.497(YOLOv3_qat::nndct_leaky_relu_185)
        self.module_186 = py_nndct.nn.Conv2d(in_channels=256, out_channels=75, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3_qat::YOLOv3_qat/ScalePrediction[layers]/ModuleList[29]/Sequential[pred]/CNNBlock[1]/Conv2d[conv]/ret.499(YOLOv3_qat::nndct_conv2d_186)
        self.module_187 = py_nndct.nn.Module('nndct_reshape') #YOLOv3_qat::YOLOv3_qat/ScalePrediction[layers]/ModuleList[29]/ret.501(YOLOv3_qat::nndct_reshape_187)
        self.module_188 = py_nndct.nn.dequant_output() #YOLOv3_qat::YOLOv3_qat/DeQuantStub[dequant_stub]/17008(YOLOv3_qat::nndct_dequant_stub_188)

    @py_nndct.nn.forward_processor
    def forward(self, *args):
        output_module_0 = self.module_0(input=args[0])
        output_module_0 = self.module_1(input=output_module_0)
        output_module_0 = self.module_2(output_module_0)
        output_module_0 = self.module_3(output_module_0)
        output_module_0 = self.module_4(output_module_0)
        output_module_0 = self.module_5(output_module_0)
        output_module_6 = self.module_6(output_module_0)
        output_module_6 = self.module_7(output_module_6)
        output_module_6 = self.module_8(output_module_6)
        output_module_6 = self.module_9(output_module_6)
        output_module_6 = self.module_10(input=output_module_6, other=output_module_0, alpha=1)
        output_module_6 = self.module_11(output_module_6)
        output_module_6 = self.module_12(output_module_6)
        output_module_13 = self.module_13(output_module_6)
        output_module_13 = self.module_14(output_module_13)
        output_module_13 = self.module_15(output_module_13)
        output_module_13 = self.module_16(output_module_13)
        output_module_13 = self.module_17(input=output_module_13, other=output_module_6, alpha=1)
        output_module_18 = self.module_18(output_module_13)
        output_module_18 = self.module_19(output_module_18)
        output_module_18 = self.module_20(output_module_18)
        output_module_18 = self.module_21(output_module_18)
        output_module_18 = self.module_22(input=output_module_18, other=output_module_13, alpha=1)
        output_module_18 = self.module_23(output_module_18)
        output_module_18 = self.module_24(output_module_18)
        output_module_25 = self.module_25(output_module_18)
        output_module_25 = self.module_26(output_module_25)
        output_module_25 = self.module_27(output_module_25)
        output_module_25 = self.module_28(output_module_25)
        output_module_25 = self.module_29(input=output_module_25, other=output_module_18, alpha=1)
        output_module_30 = self.module_30(output_module_25)
        output_module_30 = self.module_31(output_module_30)
        output_module_30 = self.module_32(output_module_30)
        output_module_30 = self.module_33(output_module_30)
        output_module_30 = self.module_34(input=output_module_30, other=output_module_25, alpha=1)
        output_module_35 = self.module_35(output_module_30)
        output_module_35 = self.module_36(output_module_35)
        output_module_35 = self.module_37(output_module_35)
        output_module_35 = self.module_38(output_module_35)
        output_module_35 = self.module_39(input=output_module_35, other=output_module_30, alpha=1)
        output_module_40 = self.module_40(output_module_35)
        output_module_40 = self.module_41(output_module_40)
        output_module_40 = self.module_42(output_module_40)
        output_module_40 = self.module_43(output_module_40)
        output_module_40 = self.module_44(input=output_module_40, other=output_module_35, alpha=1)
        output_module_45 = self.module_45(output_module_40)
        output_module_45 = self.module_46(output_module_45)
        output_module_45 = self.module_47(output_module_45)
        output_module_45 = self.module_48(output_module_45)
        output_module_45 = self.module_49(input=output_module_45, other=output_module_40, alpha=1)
        output_module_50 = self.module_50(output_module_45)
        output_module_50 = self.module_51(output_module_50)
        output_module_50 = self.module_52(output_module_50)
        output_module_50 = self.module_53(output_module_50)
        output_module_50 = self.module_54(input=output_module_50, other=output_module_45, alpha=1)
        output_module_55 = self.module_55(output_module_50)
        output_module_55 = self.module_56(output_module_55)
        output_module_55 = self.module_57(output_module_55)
        output_module_55 = self.module_58(output_module_55)
        output_module_55 = self.module_59(input=output_module_55, other=output_module_50, alpha=1)
        output_module_60 = self.module_60(output_module_55)
        output_module_60 = self.module_61(output_module_60)
        output_module_60 = self.module_62(output_module_60)
        output_module_60 = self.module_63(output_module_60)
        output_module_60 = self.module_64(input=output_module_60, other=output_module_55, alpha=1)
        output_module_65 = self.module_65(output_module_60)
        output_module_65 = self.module_66(output_module_65)
        output_module_67 = self.module_67(output_module_65)
        output_module_67 = self.module_68(output_module_67)
        output_module_67 = self.module_69(output_module_67)
        output_module_67 = self.module_70(output_module_67)
        output_module_67 = self.module_71(input=output_module_67, other=output_module_65, alpha=1)
        output_module_72 = self.module_72(output_module_67)
        output_module_72 = self.module_73(output_module_72)
        output_module_72 = self.module_74(output_module_72)
        output_module_72 = self.module_75(output_module_72)
        output_module_72 = self.module_76(input=output_module_72, other=output_module_67, alpha=1)
        output_module_77 = self.module_77(output_module_72)
        output_module_77 = self.module_78(output_module_77)
        output_module_77 = self.module_79(output_module_77)
        output_module_77 = self.module_80(output_module_77)
        output_module_77 = self.module_81(input=output_module_77, other=output_module_72, alpha=1)
        output_module_82 = self.module_82(output_module_77)
        output_module_82 = self.module_83(output_module_82)
        output_module_82 = self.module_84(output_module_82)
        output_module_82 = self.module_85(output_module_82)
        output_module_82 = self.module_86(input=output_module_82, other=output_module_77, alpha=1)
        output_module_87 = self.module_87(output_module_82)
        output_module_87 = self.module_88(output_module_87)
        output_module_87 = self.module_89(output_module_87)
        output_module_87 = self.module_90(output_module_87)
        output_module_87 = self.module_91(input=output_module_87, other=output_module_82, alpha=1)
        output_module_92 = self.module_92(output_module_87)
        output_module_92 = self.module_93(output_module_92)
        output_module_92 = self.module_94(output_module_92)
        output_module_92 = self.module_95(output_module_92)
        output_module_92 = self.module_96(input=output_module_92, other=output_module_87, alpha=1)
        output_module_97 = self.module_97(output_module_92)
        output_module_97 = self.module_98(output_module_97)
        output_module_97 = self.module_99(output_module_97)
        output_module_97 = self.module_100(output_module_97)
        output_module_97 = self.module_101(input=output_module_97, other=output_module_92, alpha=1)
        output_module_102 = self.module_102(output_module_97)
        output_module_102 = self.module_103(output_module_102)
        output_module_102 = self.module_104(output_module_102)
        output_module_102 = self.module_105(output_module_102)
        output_module_102 = self.module_106(input=output_module_102, other=output_module_97, alpha=1)
        output_module_107 = self.module_107(output_module_102)
        output_module_107 = self.module_108(output_module_107)
        output_module_109 = self.module_109(output_module_107)
        output_module_109 = self.module_110(output_module_109)
        output_module_109 = self.module_111(output_module_109)
        output_module_109 = self.module_112(output_module_109)
        output_module_109 = self.module_113(input=output_module_109, other=output_module_107, alpha=1)
        output_module_114 = self.module_114(output_module_109)
        output_module_114 = self.module_115(output_module_114)
        output_module_114 = self.module_116(output_module_114)
        output_module_114 = self.module_117(output_module_114)
        output_module_114 = self.module_118(input=output_module_114, other=output_module_109, alpha=1)
        output_module_119 = self.module_119(output_module_114)
        output_module_119 = self.module_120(output_module_119)
        output_module_119 = self.module_121(output_module_119)
        output_module_119 = self.module_122(output_module_119)
        output_module_119 = self.module_123(input=output_module_119, other=output_module_114, alpha=1)
        output_module_124 = self.module_124(output_module_119)
        output_module_124 = self.module_125(output_module_124)
        output_module_124 = self.module_126(output_module_124)
        output_module_124 = self.module_127(output_module_124)
        output_module_124 = self.module_128(input=output_module_124, other=output_module_119, alpha=1)
        output_module_124 = self.module_129(output_module_124)
        output_module_124 = self.module_130(output_module_124)
        output_module_124 = self.module_131(output_module_124)
        output_module_124 = self.module_132(output_module_124)
        output_module_124 = self.module_133(output_module_124)
        output_module_124 = self.module_134(output_module_124)
        output_module_124 = self.module_135(output_module_124)
        output_module_124 = self.module_136(output_module_124)
        output_module_124 = self.module_137(output_module_124)
        output_module_124 = self.module_138(output_module_124)
        output_module_139 = self.module_139(input=output_module_124, dim=0)
        output_module_140 = self.module_140(input=output_module_124, dim=2)
        output_module_141 = self.module_141(input=output_module_124, dim=3)
        output_module_142 = self.module_142(output_module_124)
        output_module_142 = self.module_143(output_module_142)
        output_module_142 = self.module_144(output_module_142)
        output_module_142 = self.module_145(input=output_module_142, shape=[output_module_139,3,output_module_140,output_module_141,25])
        output_module_146 = self.module_146(output_module_124)
        output_module_146 = self.module_147(output_module_146)
        output_module_146 = self.module_148(input=output_module_146, size=None, scale_factor=[2.0,2.0], mode='nearest')
        output_module_146 = self.module_149(dim=1, tensors=[output_module_146,output_module_102])
        output_module_146 = self.module_150(output_module_146)
        output_module_146 = self.module_151(output_module_146)
        output_module_146 = self.module_152(output_module_146)
        output_module_146 = self.module_153(output_module_146)
        output_module_146 = self.module_154(output_module_146)
        output_module_146 = self.module_155(output_module_146)
        output_module_146 = self.module_156(output_module_146)
        output_module_146 = self.module_157(output_module_146)
        output_module_146 = self.module_158(output_module_146)
        output_module_146 = self.module_159(output_module_146)
        output_module_160 = self.module_160(input=output_module_146, dim=0)
        output_module_161 = self.module_161(input=output_module_146, dim=2)
        output_module_162 = self.module_162(input=output_module_146, dim=3)
        output_module_163 = self.module_163(output_module_146)
        output_module_163 = self.module_164(output_module_163)
        output_module_163 = self.module_165(output_module_163)
        output_module_163 = self.module_166(input=output_module_163, shape=[output_module_160,3,output_module_161,output_module_162,25])
        output_module_167 = self.module_167(output_module_146)
        output_module_167 = self.module_168(output_module_167)
        output_module_167 = self.module_169(input=output_module_167, size=None, scale_factor=[2.0,2.0], mode='nearest')
        output_module_167 = self.module_170(dim=1, tensors=[output_module_167,output_module_60])
        output_module_167 = self.module_171(output_module_167)
        output_module_167 = self.module_172(output_module_167)
        output_module_167 = self.module_173(output_module_167)
        output_module_167 = self.module_174(output_module_167)
        output_module_167 = self.module_175(output_module_167)
        output_module_167 = self.module_176(output_module_167)
        output_module_167 = self.module_177(output_module_167)
        output_module_167 = self.module_178(output_module_167)
        output_module_167 = self.module_179(output_module_167)
        output_module_167 = self.module_180(output_module_167)
        output_module_181 = self.module_181(input=output_module_167, dim=0)
        output_module_182 = self.module_182(input=output_module_167, dim=2)
        output_module_183 = self.module_183(input=output_module_167, dim=3)
        output_module_184 = self.module_184(output_module_167)
        output_module_184 = self.module_185(output_module_184)
        output_module_184 = self.module_186(output_module_184)
        output_module_184 = self.module_187(input=output_module_184, shape=[output_module_181,3,output_module_182,output_module_183,25])
        output_module_188 = self.module_188(input=output_module_167)
        return (output_module_142,output_module_163,output_module_184)
