# GENETARED BY NNDCT, DO NOT EDIT!

import torch
from torch import tensor
import pytorch_nndct as py_nndct

class YOLOv3(py_nndct.nn.NndctQuantModel):
    def __init__(self):
        super(YOLOv3, self).__init__()
        self.module_0 = py_nndct.nn.Input() #YOLOv3::input_0(YOLOv3::nndct_input_0)
        self.module_1 = py_nndct.nn.Conv2d(in_channels=3, out_channels=32, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[0]/Conv2d[conv]/ret.3(YOLOv3::nndct_conv2d_1)
        self.module_2 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[0]/LeakyReLU[leaky]/ret.7(YOLOv3::nndct_leaky_relu_2)
        self.module_3 = py_nndct.nn.Conv2d(in_channels=32, out_channels=64, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[1]/Conv2d[conv]/ret.9(YOLOv3::nndct_conv2d_3)
        self.module_4 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[1]/LeakyReLU[leaky]/ret.13(YOLOv3::nndct_leaky_relu_4)
        self.module_5 = py_nndct.nn.Conv2d(in_channels=64, out_channels=32, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[2]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/Conv2d[conv]/ret.15(YOLOv3::nndct_conv2d_5)
        self.module_6 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[2]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/LeakyReLU[leaky]/ret.19(YOLOv3::nndct_leaky_relu_6)
        self.module_7 = py_nndct.nn.Conv2d(in_channels=32, out_channels=64, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[2]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/Conv2d[conv]/ret.21(YOLOv3::nndct_conv2d_7)
        self.module_8 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[2]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/LeakyReLU[leaky]/ret.25(YOLOv3::nndct_leaky_relu_8)
        self.module_9 = py_nndct.nn.Add() #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[2]/ret.27(YOLOv3::nndct_elemwise_add_9)
        self.module_10 = py_nndct.nn.Conv2d(in_channels=64, out_channels=128, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[3]/Conv2d[conv]/ret.29(YOLOv3::nndct_conv2d_10)
        self.module_11 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[3]/LeakyReLU[leaky]/ret.33(YOLOv3::nndct_leaky_relu_11)
        self.module_12 = py_nndct.nn.Conv2d(in_channels=128, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[4]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/Conv2d[conv]/ret.35(YOLOv3::nndct_conv2d_12)
        self.module_13 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[4]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/LeakyReLU[leaky]/ret.39(YOLOv3::nndct_leaky_relu_13)
        self.module_14 = py_nndct.nn.Conv2d(in_channels=64, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[4]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/Conv2d[conv]/ret.41(YOLOv3::nndct_conv2d_14)
        self.module_15 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[4]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/LeakyReLU[leaky]/ret.45(YOLOv3::nndct_leaky_relu_15)
        self.module_16 = py_nndct.nn.Add() #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[4]/ret.47(YOLOv3::nndct_elemwise_add_16)
        self.module_17 = py_nndct.nn.Conv2d(in_channels=128, out_channels=64, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[4]/Sequential[layers]/ModuleList[1]/CNNBlock[0]/Conv2d[conv]/ret.49(YOLOv3::nndct_conv2d_17)
        self.module_18 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[4]/Sequential[layers]/ModuleList[1]/CNNBlock[0]/LeakyReLU[leaky]/ret.53(YOLOv3::nndct_leaky_relu_18)
        self.module_19 = py_nndct.nn.Conv2d(in_channels=64, out_channels=128, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[4]/Sequential[layers]/ModuleList[1]/CNNBlock[1]/Conv2d[conv]/ret.55(YOLOv3::nndct_conv2d_19)
        self.module_20 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[4]/Sequential[layers]/ModuleList[1]/CNNBlock[1]/LeakyReLU[leaky]/ret.59(YOLOv3::nndct_leaky_relu_20)
        self.module_21 = py_nndct.nn.Add() #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[4]/ret.61(YOLOv3::nndct_elemwise_add_21)
        self.module_22 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[5]/Conv2d[conv]/ret.63(YOLOv3::nndct_conv2d_22)
        self.module_23 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[5]/LeakyReLU[leaky]/ret.67(YOLOv3::nndct_leaky_relu_23)
        self.module_24 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/Conv2d[conv]/ret.69(YOLOv3::nndct_conv2d_24)
        self.module_25 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/LeakyReLU[leaky]/ret.73(YOLOv3::nndct_leaky_relu_25)
        self.module_26 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/Conv2d[conv]/ret.75(YOLOv3::nndct_conv2d_26)
        self.module_27 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/LeakyReLU[leaky]/ret.79(YOLOv3::nndct_leaky_relu_27)
        self.module_28 = py_nndct.nn.Add() #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/ret.81(YOLOv3::nndct_elemwise_add_28)
        self.module_29 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[1]/CNNBlock[0]/Conv2d[conv]/ret.83(YOLOv3::nndct_conv2d_29)
        self.module_30 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[1]/CNNBlock[0]/LeakyReLU[leaky]/ret.87(YOLOv3::nndct_leaky_relu_30)
        self.module_31 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[1]/CNNBlock[1]/Conv2d[conv]/ret.89(YOLOv3::nndct_conv2d_31)
        self.module_32 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[1]/CNNBlock[1]/LeakyReLU[leaky]/ret.93(YOLOv3::nndct_leaky_relu_32)
        self.module_33 = py_nndct.nn.Add() #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/ret.95(YOLOv3::nndct_elemwise_add_33)
        self.module_34 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[2]/CNNBlock[0]/Conv2d[conv]/ret.97(YOLOv3::nndct_conv2d_34)
        self.module_35 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[2]/CNNBlock[0]/LeakyReLU[leaky]/ret.101(YOLOv3::nndct_leaky_relu_35)
        self.module_36 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[2]/CNNBlock[1]/Conv2d[conv]/ret.103(YOLOv3::nndct_conv2d_36)
        self.module_37 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[2]/CNNBlock[1]/LeakyReLU[leaky]/ret.107(YOLOv3::nndct_leaky_relu_37)
        self.module_38 = py_nndct.nn.Add() #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/ret.109(YOLOv3::nndct_elemwise_add_38)
        self.module_39 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[3]/CNNBlock[0]/Conv2d[conv]/ret.111(YOLOv3::nndct_conv2d_39)
        self.module_40 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[3]/CNNBlock[0]/LeakyReLU[leaky]/ret.115(YOLOv3::nndct_leaky_relu_40)
        self.module_41 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[3]/CNNBlock[1]/Conv2d[conv]/ret.117(YOLOv3::nndct_conv2d_41)
        self.module_42 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[3]/CNNBlock[1]/LeakyReLU[leaky]/ret.121(YOLOv3::nndct_leaky_relu_42)
        self.module_43 = py_nndct.nn.Add() #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/ret.123(YOLOv3::nndct_elemwise_add_43)
        self.module_44 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[4]/CNNBlock[0]/Conv2d[conv]/ret.125(YOLOv3::nndct_conv2d_44)
        self.module_45 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[4]/CNNBlock[0]/LeakyReLU[leaky]/ret.129(YOLOv3::nndct_leaky_relu_45)
        self.module_46 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[4]/CNNBlock[1]/Conv2d[conv]/ret.131(YOLOv3::nndct_conv2d_46)
        self.module_47 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[4]/CNNBlock[1]/LeakyReLU[leaky]/ret.135(YOLOv3::nndct_leaky_relu_47)
        self.module_48 = py_nndct.nn.Add() #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/ret.137(YOLOv3::nndct_elemwise_add_48)
        self.module_49 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[5]/CNNBlock[0]/Conv2d[conv]/ret.139(YOLOv3::nndct_conv2d_49)
        self.module_50 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[5]/CNNBlock[0]/LeakyReLU[leaky]/ret.143(YOLOv3::nndct_leaky_relu_50)
        self.module_51 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[5]/CNNBlock[1]/Conv2d[conv]/ret.145(YOLOv3::nndct_conv2d_51)
        self.module_52 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[5]/CNNBlock[1]/LeakyReLU[leaky]/ret.149(YOLOv3::nndct_leaky_relu_52)
        self.module_53 = py_nndct.nn.Add() #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/ret.151(YOLOv3::nndct_elemwise_add_53)
        self.module_54 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[6]/CNNBlock[0]/Conv2d[conv]/ret.153(YOLOv3::nndct_conv2d_54)
        self.module_55 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[6]/CNNBlock[0]/LeakyReLU[leaky]/ret.157(YOLOv3::nndct_leaky_relu_55)
        self.module_56 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[6]/CNNBlock[1]/Conv2d[conv]/ret.159(YOLOv3::nndct_conv2d_56)
        self.module_57 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[6]/CNNBlock[1]/LeakyReLU[leaky]/ret.163(YOLOv3::nndct_leaky_relu_57)
        self.module_58 = py_nndct.nn.Add() #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/ret.165(YOLOv3::nndct_elemwise_add_58)
        self.module_59 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[7]/CNNBlock[0]/Conv2d[conv]/ret.167(YOLOv3::nndct_conv2d_59)
        self.module_60 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[7]/CNNBlock[0]/LeakyReLU[leaky]/ret.171(YOLOv3::nndct_leaky_relu_60)
        self.module_61 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[7]/CNNBlock[1]/Conv2d[conv]/ret.173(YOLOv3::nndct_conv2d_61)
        self.module_62 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/Sequential[layers]/ModuleList[7]/CNNBlock[1]/LeakyReLU[leaky]/ret.177(YOLOv3::nndct_leaky_relu_62)
        self.module_63 = py_nndct.nn.Add() #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[6]/ret.179(YOLOv3::nndct_elemwise_add_63)
        self.module_64 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[7]/Conv2d[conv]/ret.181(YOLOv3::nndct_conv2d_64)
        self.module_65 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[7]/LeakyReLU[leaky]/ret.185(YOLOv3::nndct_leaky_relu_65)
        self.module_66 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/Conv2d[conv]/ret.187(YOLOv3::nndct_conv2d_66)
        self.module_67 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/LeakyReLU[leaky]/ret.191(YOLOv3::nndct_leaky_relu_67)
        self.module_68 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/Conv2d[conv]/ret.193(YOLOv3::nndct_conv2d_68)
        self.module_69 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/LeakyReLU[leaky]/ret.197(YOLOv3::nndct_leaky_relu_69)
        self.module_70 = py_nndct.nn.Add() #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/ret.199(YOLOv3::nndct_elemwise_add_70)
        self.module_71 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[1]/CNNBlock[0]/Conv2d[conv]/ret.201(YOLOv3::nndct_conv2d_71)
        self.module_72 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[1]/CNNBlock[0]/LeakyReLU[leaky]/ret.205(YOLOv3::nndct_leaky_relu_72)
        self.module_73 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[1]/CNNBlock[1]/Conv2d[conv]/ret.207(YOLOv3::nndct_conv2d_73)
        self.module_74 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[1]/CNNBlock[1]/LeakyReLU[leaky]/ret.211(YOLOv3::nndct_leaky_relu_74)
        self.module_75 = py_nndct.nn.Add() #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/ret.213(YOLOv3::nndct_elemwise_add_75)
        self.module_76 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[2]/CNNBlock[0]/Conv2d[conv]/ret.215(YOLOv3::nndct_conv2d_76)
        self.module_77 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[2]/CNNBlock[0]/LeakyReLU[leaky]/ret.219(YOLOv3::nndct_leaky_relu_77)
        self.module_78 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[2]/CNNBlock[1]/Conv2d[conv]/ret.221(YOLOv3::nndct_conv2d_78)
        self.module_79 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[2]/CNNBlock[1]/LeakyReLU[leaky]/ret.225(YOLOv3::nndct_leaky_relu_79)
        self.module_80 = py_nndct.nn.Add() #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/ret.227(YOLOv3::nndct_elemwise_add_80)
        self.module_81 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[3]/CNNBlock[0]/Conv2d[conv]/ret.229(YOLOv3::nndct_conv2d_81)
        self.module_82 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[3]/CNNBlock[0]/LeakyReLU[leaky]/ret.233(YOLOv3::nndct_leaky_relu_82)
        self.module_83 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[3]/CNNBlock[1]/Conv2d[conv]/ret.235(YOLOv3::nndct_conv2d_83)
        self.module_84 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[3]/CNNBlock[1]/LeakyReLU[leaky]/ret.239(YOLOv3::nndct_leaky_relu_84)
        self.module_85 = py_nndct.nn.Add() #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/ret.241(YOLOv3::nndct_elemwise_add_85)
        self.module_86 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[4]/CNNBlock[0]/Conv2d[conv]/ret.243(YOLOv3::nndct_conv2d_86)
        self.module_87 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[4]/CNNBlock[0]/LeakyReLU[leaky]/ret.247(YOLOv3::nndct_leaky_relu_87)
        self.module_88 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[4]/CNNBlock[1]/Conv2d[conv]/ret.249(YOLOv3::nndct_conv2d_88)
        self.module_89 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[4]/CNNBlock[1]/LeakyReLU[leaky]/ret.253(YOLOv3::nndct_leaky_relu_89)
        self.module_90 = py_nndct.nn.Add() #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/ret.255(YOLOv3::nndct_elemwise_add_90)
        self.module_91 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[5]/CNNBlock[0]/Conv2d[conv]/ret.257(YOLOv3::nndct_conv2d_91)
        self.module_92 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[5]/CNNBlock[0]/LeakyReLU[leaky]/ret.261(YOLOv3::nndct_leaky_relu_92)
        self.module_93 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[5]/CNNBlock[1]/Conv2d[conv]/ret.263(YOLOv3::nndct_conv2d_93)
        self.module_94 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[5]/CNNBlock[1]/LeakyReLU[leaky]/ret.267(YOLOv3::nndct_leaky_relu_94)
        self.module_95 = py_nndct.nn.Add() #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/ret.269(YOLOv3::nndct_elemwise_add_95)
        self.module_96 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[6]/CNNBlock[0]/Conv2d[conv]/ret.271(YOLOv3::nndct_conv2d_96)
        self.module_97 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[6]/CNNBlock[0]/LeakyReLU[leaky]/ret.275(YOLOv3::nndct_leaky_relu_97)
        self.module_98 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[6]/CNNBlock[1]/Conv2d[conv]/ret.277(YOLOv3::nndct_conv2d_98)
        self.module_99 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[6]/CNNBlock[1]/LeakyReLU[leaky]/ret.281(YOLOv3::nndct_leaky_relu_99)
        self.module_100 = py_nndct.nn.Add() #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/ret.283(YOLOv3::nndct_elemwise_add_100)
        self.module_101 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[7]/CNNBlock[0]/Conv2d[conv]/ret.285(YOLOv3::nndct_conv2d_101)
        self.module_102 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[7]/CNNBlock[0]/LeakyReLU[leaky]/ret.289(YOLOv3::nndct_leaky_relu_102)
        self.module_103 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[7]/CNNBlock[1]/Conv2d[conv]/ret.291(YOLOv3::nndct_conv2d_103)
        self.module_104 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/Sequential[layers]/ModuleList[7]/CNNBlock[1]/LeakyReLU[leaky]/ret.295(YOLOv3::nndct_leaky_relu_104)
        self.module_105 = py_nndct.nn.Add() #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[8]/ret.297(YOLOv3::nndct_elemwise_add_105)
        self.module_106 = py_nndct.nn.Conv2d(in_channels=512, out_channels=1024, kernel_size=[3, 3], stride=[2, 2], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[9]/Conv2d[conv]/ret.299(YOLOv3::nndct_conv2d_106)
        self.module_107 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[9]/LeakyReLU[leaky]/ret.303(YOLOv3::nndct_leaky_relu_107)
        self.module_108 = py_nndct.nn.Conv2d(in_channels=1024, out_channels=512, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/Conv2d[conv]/ret.305(YOLOv3::nndct_conv2d_108)
        self.module_109 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/LeakyReLU[leaky]/ret.309(YOLOv3::nndct_leaky_relu_109)
        self.module_110 = py_nndct.nn.Conv2d(in_channels=512, out_channels=1024, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/Conv2d[conv]/ret.311(YOLOv3::nndct_conv2d_110)
        self.module_111 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/LeakyReLU[leaky]/ret.315(YOLOv3::nndct_leaky_relu_111)
        self.module_112 = py_nndct.nn.Add() #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[10]/ret.317(YOLOv3::nndct_elemwise_add_112)
        self.module_113 = py_nndct.nn.Conv2d(in_channels=1024, out_channels=512, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[1]/CNNBlock[0]/Conv2d[conv]/ret.319(YOLOv3::nndct_conv2d_113)
        self.module_114 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[1]/CNNBlock[0]/LeakyReLU[leaky]/ret.323(YOLOv3::nndct_leaky_relu_114)
        self.module_115 = py_nndct.nn.Conv2d(in_channels=512, out_channels=1024, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[1]/CNNBlock[1]/Conv2d[conv]/ret.325(YOLOv3::nndct_conv2d_115)
        self.module_116 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[1]/CNNBlock[1]/LeakyReLU[leaky]/ret.329(YOLOv3::nndct_leaky_relu_116)
        self.module_117 = py_nndct.nn.Add() #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[10]/ret.331(YOLOv3::nndct_elemwise_add_117)
        self.module_118 = py_nndct.nn.Conv2d(in_channels=1024, out_channels=512, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[2]/CNNBlock[0]/Conv2d[conv]/ret.333(YOLOv3::nndct_conv2d_118)
        self.module_119 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[2]/CNNBlock[0]/LeakyReLU[leaky]/ret.337(YOLOv3::nndct_leaky_relu_119)
        self.module_120 = py_nndct.nn.Conv2d(in_channels=512, out_channels=1024, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[2]/CNNBlock[1]/Conv2d[conv]/ret.339(YOLOv3::nndct_conv2d_120)
        self.module_121 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[2]/CNNBlock[1]/LeakyReLU[leaky]/ret.343(YOLOv3::nndct_leaky_relu_121)
        self.module_122 = py_nndct.nn.Add() #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[10]/ret.345(YOLOv3::nndct_elemwise_add_122)
        self.module_123 = py_nndct.nn.Conv2d(in_channels=1024, out_channels=512, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[3]/CNNBlock[0]/Conv2d[conv]/ret.347(YOLOv3::nndct_conv2d_123)
        self.module_124 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[3]/CNNBlock[0]/LeakyReLU[leaky]/ret.351(YOLOv3::nndct_leaky_relu_124)
        self.module_125 = py_nndct.nn.Conv2d(in_channels=512, out_channels=1024, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[3]/CNNBlock[1]/Conv2d[conv]/ret.353(YOLOv3::nndct_conv2d_125)
        self.module_126 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[10]/Sequential[layers]/ModuleList[3]/CNNBlock[1]/LeakyReLU[leaky]/ret.357(YOLOv3::nndct_leaky_relu_126)
        self.module_127 = py_nndct.nn.Add() #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[10]/ret.359(YOLOv3::nndct_elemwise_add_127)
        self.module_128 = py_nndct.nn.Conv2d(in_channels=1024, out_channels=512, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[11]/Conv2d[conv]/ret.361(YOLOv3::nndct_conv2d_128)
        self.module_129 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[11]/LeakyReLU[leaky]/ret.365(YOLOv3::nndct_leaky_relu_129)
        self.module_130 = py_nndct.nn.Conv2d(in_channels=512, out_channels=1024, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[12]/Conv2d[conv]/ret.367(YOLOv3::nndct_conv2d_130)
        self.module_131 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[12]/LeakyReLU[leaky]/ret.371(YOLOv3::nndct_leaky_relu_131)
        self.module_132 = py_nndct.nn.Conv2d(in_channels=1024, out_channels=512, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[13]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/Conv2d[conv]/ret.373(YOLOv3::nndct_conv2d_132)
        self.module_133 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[13]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/LeakyReLU[leaky]/ret.377(YOLOv3::nndct_leaky_relu_133)
        self.module_134 = py_nndct.nn.Conv2d(in_channels=512, out_channels=1024, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[13]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/Conv2d[conv]/ret.379(YOLOv3::nndct_conv2d_134)
        self.module_135 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[13]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/LeakyReLU[leaky]/ret.383(YOLOv3::nndct_leaky_relu_135)
        self.module_136 = py_nndct.nn.Conv2d(in_channels=1024, out_channels=512, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[14]/Conv2d[conv]/ret.385(YOLOv3::nndct_conv2d_136)
        self.module_137 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[14]/LeakyReLU[leaky]/ret.389(YOLOv3::nndct_leaky_relu_137)
        self.module_138 = py_nndct.nn.Conv2d(in_channels=512, out_channels=1024, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ScalePrediction[layers]/ModuleList[15]/Sequential[pred]/CNNBlock[0]/Conv2d[conv]/ret.391(YOLOv3::nndct_conv2d_138)
        self.module_139 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ScalePrediction[layers]/ModuleList[15]/Sequential[pred]/CNNBlock[0]/LeakyReLU[leaky]/ret.395(YOLOv3::nndct_leaky_relu_139)
        self.module_140 = py_nndct.nn.Conv2d(in_channels=1024, out_channels=75, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ScalePrediction[layers]/ModuleList[15]/Sequential[pred]/CNNBlock[1]/Conv2d[conv]/ret.397(YOLOv3::nndct_conv2d_140)
        self.module_141 = py_nndct.nn.Module('nndct_shape') #YOLOv3::YOLOv3/ScalePrediction[layers]/ModuleList[15]/16682(YOLOv3::nndct_shape_141)
        self.module_142 = py_nndct.nn.Module('nndct_shape') #YOLOv3::YOLOv3/ScalePrediction[layers]/ModuleList[15]/16705(YOLOv3::nndct_shape_142)
        self.module_143 = py_nndct.nn.Module('nndct_shape') #YOLOv3::YOLOv3/ScalePrediction[layers]/ModuleList[15]/16725(YOLOv3::nndct_shape_143)
        self.module_144 = py_nndct.nn.Module('nndct_reshape') #YOLOv3::YOLOv3/ScalePrediction[layers]/ModuleList[15]/ret.399(YOLOv3::nndct_reshape_144)
        self.module_145 = py_nndct.nn.Module('nndct_permute') #YOLOv3::YOLOv3/ScalePrediction[layers]/ModuleList[15]/ret.401(YOLOv3::nndct_permute_145)
        self.module_146 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[16]/Conv2d[conv]/ret.403(YOLOv3::nndct_conv2d_146)
        self.module_147 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[16]/LeakyReLU[leaky]/ret.407(YOLOv3::nndct_leaky_relu_147)
        self.module_148 = py_nndct.nn.Interpolate() #YOLOv3::YOLOv3/Upsample[layers]/ModuleList[17]/ret.409(YOLOv3::nndct_resize_148)
        self.module_149 = py_nndct.nn.Cat() #YOLOv3::YOLOv3/ret.411(YOLOv3::nndct_concat_149)
        self.module_150 = py_nndct.nn.Conv2d(in_channels=768, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[18]/Conv2d[conv]/ret.413(YOLOv3::nndct_conv2d_150)
        self.module_151 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[18]/LeakyReLU[leaky]/ret.417(YOLOv3::nndct_leaky_relu_151)
        self.module_152 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[19]/Conv2d[conv]/ret.419(YOLOv3::nndct_conv2d_152)
        self.module_153 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[19]/LeakyReLU[leaky]/ret.423(YOLOv3::nndct_leaky_relu_153)
        self.module_154 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[20]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/Conv2d[conv]/ret.425(YOLOv3::nndct_conv2d_154)
        self.module_155 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[20]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/LeakyReLU[leaky]/ret.429(YOLOv3::nndct_leaky_relu_155)
        self.module_156 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[20]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/Conv2d[conv]/ret.431(YOLOv3::nndct_conv2d_156)
        self.module_157 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[20]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/LeakyReLU[leaky]/ret.435(YOLOv3::nndct_leaky_relu_157)
        self.module_158 = py_nndct.nn.Conv2d(in_channels=512, out_channels=256, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[21]/Conv2d[conv]/ret.437(YOLOv3::nndct_conv2d_158)
        self.module_159 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[21]/LeakyReLU[leaky]/ret.441(YOLOv3::nndct_leaky_relu_159)
        self.module_160 = py_nndct.nn.Conv2d(in_channels=256, out_channels=512, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ScalePrediction[layers]/ModuleList[22]/Sequential[pred]/CNNBlock[0]/Conv2d[conv]/ret.443(YOLOv3::nndct_conv2d_160)
        self.module_161 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ScalePrediction[layers]/ModuleList[22]/Sequential[pred]/CNNBlock[0]/LeakyReLU[leaky]/ret.447(YOLOv3::nndct_leaky_relu_161)
        self.module_162 = py_nndct.nn.Conv2d(in_channels=512, out_channels=75, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ScalePrediction[layers]/ModuleList[22]/Sequential[pred]/CNNBlock[1]/Conv2d[conv]/ret.449(YOLOv3::nndct_conv2d_162)
        self.module_163 = py_nndct.nn.Module('nndct_shape') #YOLOv3::YOLOv3/ScalePrediction[layers]/ModuleList[22]/16986(YOLOv3::nndct_shape_163)
        self.module_164 = py_nndct.nn.Module('nndct_shape') #YOLOv3::YOLOv3/ScalePrediction[layers]/ModuleList[22]/17009(YOLOv3::nndct_shape_164)
        self.module_165 = py_nndct.nn.Module('nndct_shape') #YOLOv3::YOLOv3/ScalePrediction[layers]/ModuleList[22]/17029(YOLOv3::nndct_shape_165)
        self.module_166 = py_nndct.nn.Module('nndct_reshape') #YOLOv3::YOLOv3/ScalePrediction[layers]/ModuleList[22]/ret.451(YOLOv3::nndct_reshape_166)
        self.module_167 = py_nndct.nn.Module('nndct_permute') #YOLOv3::YOLOv3/ScalePrediction[layers]/ModuleList[22]/ret.453(YOLOv3::nndct_permute_167)
        self.module_168 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[23]/Conv2d[conv]/ret.455(YOLOv3::nndct_conv2d_168)
        self.module_169 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[23]/LeakyReLU[leaky]/ret.459(YOLOv3::nndct_leaky_relu_169)
        self.module_170 = py_nndct.nn.Interpolate() #YOLOv3::YOLOv3/Upsample[layers]/ModuleList[24]/ret.461(YOLOv3::nndct_resize_170)
        self.module_171 = py_nndct.nn.Cat() #YOLOv3::YOLOv3/ret.463(YOLOv3::nndct_concat_171)
        self.module_172 = py_nndct.nn.Conv2d(in_channels=384, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[25]/Conv2d[conv]/ret.465(YOLOv3::nndct_conv2d_172)
        self.module_173 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[25]/LeakyReLU[leaky]/ret.469(YOLOv3::nndct_leaky_relu_173)
        self.module_174 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[26]/Conv2d[conv]/ret.471(YOLOv3::nndct_conv2d_174)
        self.module_175 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[26]/LeakyReLU[leaky]/ret.475(YOLOv3::nndct_leaky_relu_175)
        self.module_176 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[27]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/Conv2d[conv]/ret.477(YOLOv3::nndct_conv2d_176)
        self.module_177 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[27]/Sequential[layers]/ModuleList[0]/CNNBlock[0]/LeakyReLU[leaky]/ret.481(YOLOv3::nndct_leaky_relu_177)
        self.module_178 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[27]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/Conv2d[conv]/ret.483(YOLOv3::nndct_conv2d_178)
        self.module_179 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ResidualBlock[layers]/ModuleList[27]/Sequential[layers]/ModuleList[0]/CNNBlock[1]/LeakyReLU[leaky]/ret.487(YOLOv3::nndct_leaky_relu_179)
        self.module_180 = py_nndct.nn.Conv2d(in_channels=256, out_channels=128, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[28]/Conv2d[conv]/ret.489(YOLOv3::nndct_conv2d_180)
        self.module_181 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/CNNBlock[layers]/ModuleList[28]/LeakyReLU[leaky]/ret.493(YOLOv3::nndct_leaky_relu_181)
        self.module_182 = py_nndct.nn.Conv2d(in_channels=128, out_channels=256, kernel_size=[3, 3], stride=[1, 1], padding=[1, 1], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ScalePrediction[layers]/ModuleList[29]/Sequential[pred]/CNNBlock[0]/Conv2d[conv]/ret.495(YOLOv3::nndct_conv2d_182)
        self.module_183 = py_nndct.nn.LeakyReLU(negative_slope=0.1, inplace=False) #YOLOv3::YOLOv3/ScalePrediction[layers]/ModuleList[29]/Sequential[pred]/CNNBlock[0]/LeakyReLU[leaky]/ret.499(YOLOv3::nndct_leaky_relu_183)
        self.module_184 = py_nndct.nn.Conv2d(in_channels=256, out_channels=75, kernel_size=[1, 1], stride=[1, 1], padding=[0, 0], dilation=[1, 1], groups=1, bias=True) #YOLOv3::YOLOv3/ScalePrediction[layers]/ModuleList[29]/Sequential[pred]/CNNBlock[1]/Conv2d[conv]/ret.501(YOLOv3::nndct_conv2d_184)
        self.module_185 = py_nndct.nn.Module('nndct_shape') #YOLOv3::YOLOv3/ScalePrediction[layers]/ModuleList[29]/17290(YOLOv3::nndct_shape_185)
        self.module_186 = py_nndct.nn.Module('nndct_shape') #YOLOv3::YOLOv3/ScalePrediction[layers]/ModuleList[29]/17313(YOLOv3::nndct_shape_186)
        self.module_187 = py_nndct.nn.Module('nndct_shape') #YOLOv3::YOLOv3/ScalePrediction[layers]/ModuleList[29]/17333(YOLOv3::nndct_shape_187)
        self.module_188 = py_nndct.nn.Module('nndct_reshape') #YOLOv3::YOLOv3/ScalePrediction[layers]/ModuleList[29]/ret.503(YOLOv3::nndct_reshape_188)
        self.module_189 = py_nndct.nn.Module('nndct_permute') #YOLOv3::YOLOv3/ScalePrediction[layers]/ModuleList[29]/ret(YOLOv3::nndct_permute_189)

    @py_nndct.nn.forward_processor
    def forward(self, *args):
        output_module_0 = self.module_0(input=args[0])
        output_module_0 = self.module_1(output_module_0)
        output_module_0 = self.module_2(output_module_0)
        output_module_0 = self.module_3(output_module_0)
        output_module_0 = self.module_4(output_module_0)
        output_module_5 = self.module_5(output_module_0)
        output_module_5 = self.module_6(output_module_5)
        output_module_5 = self.module_7(output_module_5)
        output_module_5 = self.module_8(output_module_5)
        output_module_9 = self.module_9(input=output_module_0, other=output_module_5, alpha=1)
        output_module_9 = self.module_10(output_module_9)
        output_module_9 = self.module_11(output_module_9)
        output_module_12 = self.module_12(output_module_9)
        output_module_12 = self.module_13(output_module_12)
        output_module_12 = self.module_14(output_module_12)
        output_module_12 = self.module_15(output_module_12)
        output_module_16 = self.module_16(input=output_module_9, other=output_module_12, alpha=1)
        output_module_17 = self.module_17(output_module_16)
        output_module_17 = self.module_18(output_module_17)
        output_module_17 = self.module_19(output_module_17)
        output_module_17 = self.module_20(output_module_17)
        output_module_21 = self.module_21(input=output_module_16, other=output_module_17, alpha=1)
        output_module_21 = self.module_22(output_module_21)
        output_module_21 = self.module_23(output_module_21)
        output_module_24 = self.module_24(output_module_21)
        output_module_24 = self.module_25(output_module_24)
        output_module_24 = self.module_26(output_module_24)
        output_module_24 = self.module_27(output_module_24)
        output_module_28 = self.module_28(input=output_module_21, other=output_module_24, alpha=1)
        output_module_29 = self.module_29(output_module_28)
        output_module_29 = self.module_30(output_module_29)
        output_module_29 = self.module_31(output_module_29)
        output_module_29 = self.module_32(output_module_29)
        output_module_33 = self.module_33(input=output_module_28, other=output_module_29, alpha=1)
        output_module_34 = self.module_34(output_module_33)
        output_module_34 = self.module_35(output_module_34)
        output_module_34 = self.module_36(output_module_34)
        output_module_34 = self.module_37(output_module_34)
        output_module_38 = self.module_38(input=output_module_33, other=output_module_34, alpha=1)
        output_module_39 = self.module_39(output_module_38)
        output_module_39 = self.module_40(output_module_39)
        output_module_39 = self.module_41(output_module_39)
        output_module_39 = self.module_42(output_module_39)
        output_module_43 = self.module_43(input=output_module_38, other=output_module_39, alpha=1)
        output_module_44 = self.module_44(output_module_43)
        output_module_44 = self.module_45(output_module_44)
        output_module_44 = self.module_46(output_module_44)
        output_module_44 = self.module_47(output_module_44)
        output_module_48 = self.module_48(input=output_module_43, other=output_module_44, alpha=1)
        output_module_49 = self.module_49(output_module_48)
        output_module_49 = self.module_50(output_module_49)
        output_module_49 = self.module_51(output_module_49)
        output_module_49 = self.module_52(output_module_49)
        output_module_53 = self.module_53(input=output_module_48, other=output_module_49, alpha=1)
        output_module_54 = self.module_54(output_module_53)
        output_module_54 = self.module_55(output_module_54)
        output_module_54 = self.module_56(output_module_54)
        output_module_54 = self.module_57(output_module_54)
        output_module_58 = self.module_58(input=output_module_53, other=output_module_54, alpha=1)
        output_module_59 = self.module_59(output_module_58)
        output_module_59 = self.module_60(output_module_59)
        output_module_59 = self.module_61(output_module_59)
        output_module_59 = self.module_62(output_module_59)
        output_module_63 = self.module_63(input=output_module_58, other=output_module_59, alpha=1)
        output_module_64 = self.module_64(output_module_63)
        output_module_64 = self.module_65(output_module_64)
        output_module_66 = self.module_66(output_module_64)
        output_module_66 = self.module_67(output_module_66)
        output_module_66 = self.module_68(output_module_66)
        output_module_66 = self.module_69(output_module_66)
        output_module_70 = self.module_70(input=output_module_64, other=output_module_66, alpha=1)
        output_module_71 = self.module_71(output_module_70)
        output_module_71 = self.module_72(output_module_71)
        output_module_71 = self.module_73(output_module_71)
        output_module_71 = self.module_74(output_module_71)
        output_module_75 = self.module_75(input=output_module_70, other=output_module_71, alpha=1)
        output_module_76 = self.module_76(output_module_75)
        output_module_76 = self.module_77(output_module_76)
        output_module_76 = self.module_78(output_module_76)
        output_module_76 = self.module_79(output_module_76)
        output_module_80 = self.module_80(input=output_module_75, other=output_module_76, alpha=1)
        output_module_81 = self.module_81(output_module_80)
        output_module_81 = self.module_82(output_module_81)
        output_module_81 = self.module_83(output_module_81)
        output_module_81 = self.module_84(output_module_81)
        output_module_85 = self.module_85(input=output_module_80, other=output_module_81, alpha=1)
        output_module_86 = self.module_86(output_module_85)
        output_module_86 = self.module_87(output_module_86)
        output_module_86 = self.module_88(output_module_86)
        output_module_86 = self.module_89(output_module_86)
        output_module_90 = self.module_90(input=output_module_85, other=output_module_86, alpha=1)
        output_module_91 = self.module_91(output_module_90)
        output_module_91 = self.module_92(output_module_91)
        output_module_91 = self.module_93(output_module_91)
        output_module_91 = self.module_94(output_module_91)
        output_module_95 = self.module_95(input=output_module_90, other=output_module_91, alpha=1)
        output_module_96 = self.module_96(output_module_95)
        output_module_96 = self.module_97(output_module_96)
        output_module_96 = self.module_98(output_module_96)
        output_module_96 = self.module_99(output_module_96)
        output_module_100 = self.module_100(input=output_module_95, other=output_module_96, alpha=1)
        output_module_101 = self.module_101(output_module_100)
        output_module_101 = self.module_102(output_module_101)
        output_module_101 = self.module_103(output_module_101)
        output_module_101 = self.module_104(output_module_101)
        output_module_105 = self.module_105(input=output_module_100, other=output_module_101, alpha=1)
        output_module_106 = self.module_106(output_module_105)
        output_module_106 = self.module_107(output_module_106)
        output_module_108 = self.module_108(output_module_106)
        output_module_108 = self.module_109(output_module_108)
        output_module_108 = self.module_110(output_module_108)
        output_module_108 = self.module_111(output_module_108)
        output_module_112 = self.module_112(input=output_module_106, other=output_module_108, alpha=1)
        output_module_113 = self.module_113(output_module_112)
        output_module_113 = self.module_114(output_module_113)
        output_module_113 = self.module_115(output_module_113)
        output_module_113 = self.module_116(output_module_113)
        output_module_117 = self.module_117(input=output_module_112, other=output_module_113, alpha=1)
        output_module_118 = self.module_118(output_module_117)
        output_module_118 = self.module_119(output_module_118)
        output_module_118 = self.module_120(output_module_118)
        output_module_118 = self.module_121(output_module_118)
        output_module_122 = self.module_122(input=output_module_117, other=output_module_118, alpha=1)
        output_module_123 = self.module_123(output_module_122)
        output_module_123 = self.module_124(output_module_123)
        output_module_123 = self.module_125(output_module_123)
        output_module_123 = self.module_126(output_module_123)
        output_module_127 = self.module_127(input=output_module_122, other=output_module_123, alpha=1)
        output_module_127 = self.module_128(output_module_127)
        output_module_127 = self.module_129(output_module_127)
        output_module_127 = self.module_130(output_module_127)
        output_module_127 = self.module_131(output_module_127)
        output_module_127 = self.module_132(output_module_127)
        output_module_127 = self.module_133(output_module_127)
        output_module_127 = self.module_134(output_module_127)
        output_module_127 = self.module_135(output_module_127)
        output_module_127 = self.module_136(output_module_127)
        output_module_127 = self.module_137(output_module_127)
        output_module_138 = self.module_138(output_module_127)
        output_module_138 = self.module_139(output_module_138)
        output_module_138 = self.module_140(output_module_138)
        output_module_141 = self.module_141(input=output_module_127, dim=0)
        output_module_142 = self.module_142(input=output_module_127, dim=2)
        output_module_143 = self.module_143(input=output_module_127, dim=3)
        output_module_138 = self.module_144(input=output_module_138, shape=[output_module_141,3,25,output_module_142,output_module_143])
        output_module_138 = self.module_145(dims=[0,1,3,4,2], input=output_module_138)
        output_module_146 = self.module_146(output_module_127)
        output_module_146 = self.module_147(output_module_146)
        output_module_146 = self.module_148(input=output_module_146, size=None, scale_factor=[2.0,2.0], mode='nearest')
        output_module_146 = self.module_149(dim=1, tensors=[output_module_146,output_module_105])
        output_module_146 = self.module_150(output_module_146)
        output_module_146 = self.module_151(output_module_146)
        output_module_146 = self.module_152(output_module_146)
        output_module_146 = self.module_153(output_module_146)
        output_module_146 = self.module_154(output_module_146)
        output_module_146 = self.module_155(output_module_146)
        output_module_146 = self.module_156(output_module_146)
        output_module_146 = self.module_157(output_module_146)
        output_module_146 = self.module_158(output_module_146)
        output_module_146 = self.module_159(output_module_146)
        output_module_160 = self.module_160(output_module_146)
        output_module_160 = self.module_161(output_module_160)
        output_module_160 = self.module_162(output_module_160)
        output_module_163 = self.module_163(input=output_module_146, dim=0)
        output_module_164 = self.module_164(input=output_module_146, dim=2)
        output_module_165 = self.module_165(input=output_module_146, dim=3)
        output_module_160 = self.module_166(input=output_module_160, shape=[output_module_163,3,25,output_module_164,output_module_165])
        output_module_160 = self.module_167(dims=[0,1,3,4,2], input=output_module_160)
        output_module_168 = self.module_168(output_module_146)
        output_module_168 = self.module_169(output_module_168)
        output_module_168 = self.module_170(input=output_module_168, size=None, scale_factor=[2.0,2.0], mode='nearest')
        output_module_168 = self.module_171(dim=1, tensors=[output_module_168,output_module_63])
        output_module_168 = self.module_172(output_module_168)
        output_module_168 = self.module_173(output_module_168)
        output_module_168 = self.module_174(output_module_168)
        output_module_168 = self.module_175(output_module_168)
        output_module_168 = self.module_176(output_module_168)
        output_module_168 = self.module_177(output_module_168)
        output_module_168 = self.module_178(output_module_168)
        output_module_168 = self.module_179(output_module_168)
        output_module_168 = self.module_180(output_module_168)
        output_module_168 = self.module_181(output_module_168)
        output_module_182 = self.module_182(output_module_168)
        output_module_182 = self.module_183(output_module_182)
        output_module_182 = self.module_184(output_module_182)
        output_module_185 = self.module_185(input=output_module_168, dim=0)
        output_module_186 = self.module_186(input=output_module_168, dim=2)
        output_module_187 = self.module_187(input=output_module_168, dim=3)
        output_module_182 = self.module_188(input=output_module_182, shape=[output_module_185,3,25,output_module_186,output_module_187])
        output_module_182 = self.module_189(dims=[0,1,3,4,2], input=output_module_182)
        return (output_module_138,output_module_160,output_module_182)
